CREATE TABLE `blogPosts` (
`postId` INT  PRIMARY KEY NOT NULL AUTO_INCREMENT,
`title` VARCHAR(200)  NOT NULL,
`slug` VARCHAR(200)  UNIQUE NOT NULL,
`content` TEXT  NOT NULL,
`coverImage` VARCHAR(255)  NULL,
`status` ENUM('published', 'draft')  NOT NULL,
`blogPostCreatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
`blogPostUpdatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`blogPostIdentify` VARCHAR(50)  NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;