CREATE TABLE `campaign` (
`campaignId` INT  PRIMARY KEY NOT NULL AUTO_INCREMENT,
`campaignTitle` VARCHAR(255)  NULL,
`campaignSlogan` VARCHAR(255)  NULL,
`campaignMedia` VARCHAR(255)  NULL,
`campaignAction` VARCHAR(255)  NULL,
`campaignCreatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
`campaignUpdatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`campaignIdentify` VARCHAR(50)  NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;