CREATE TABLE `clients` (
`clientId` INT  PRIMARY KEY NOT NULL AUTO_INCREMENT,
`clientName` VARCHAR(250)  NULL,
`clientEmail` VARCHAR(250)  NULL,
`clientMobile` VARCHAR(20)  NULL,
`clientAddress` VARCHAR(1000)  NULL,
`clientImage` VARCHAR(255)  NULL,
`clientReference` VARCHAR(500)  NULL,
`clientCreatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
`clientUpdatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`clientIdentify` VARCHAR(50)  NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;