CREATE TABLE `dimention` (
`id` INT  PRIMARY KEY NOT NULL AUTO_INCREMENT,
`boo` BOOLEAN  NOT NULL,
`floa` FLOAT(8,2)  NOT NULL,
`deci` DECIMAL(10,2)  NOT NULL,
`doub` DOUBLE(10,4)  NOT NULL,
`dimentionCreatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
`dimentionUpdatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`dimentionIdentify` VARCHAR(50)  NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;