CREATE TABLE `events` (
`eventId` INT  PRIMARY KEY NOT NULL AUTO_INCREMENT,
`eventTitle` VARCHAR(255)  NOT NULL,
`eventDescription` VARCHAR(500)  NOT NULL,
`eventDate` TIMESTAMP  NULL,
`location` VARCHAR(255)  NOT NULL,
`organisedBy` VARCHAR(255)  NOT NULL,
`eventFeatureImage` VARCHAR(255)  NOT NULL,
`eventCreatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
`eventUpdatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`eventIdentify` VARCHAR(50)  NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;