CREATE TABLE `event_gallery` (
`galleryId` INT  PRIMARY KEY NOT NULL AUTO_INCREMENT,
`eventId` INT  NOT NULL,
`galleryMedia` VARCHAR(255)  NULL,
`caption` VARCHAR(250)  NULL,
`event_galleryCreatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
`event_galleryUpdatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`event_galleryIdentify` VARCHAR(50)  NOT NULL,
FOREIGN KEY (`eventId`) REFERENCES `events`(`eventId`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;