CREATE TABLE `faqs` (
`faqId` INT  PRIMARY KEY NOT NULL AUTO_INCREMENT,
`question` VARCHAR(255)  NOT NULL,
`answer` TEXT  NOT NULL,
`faqCreatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
`faqUpdatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`faqIdentify` VARCHAR(50)  NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;