CREATE TABLE `galleries` (
`galleryId` INT  PRIMARY KEY NOT NULL AUTO_INCREMENT,
`galleryMedia` VARCHAR(255)  NULL,
`caption` VARCHAR(255)  NULL,
`eventId` INT  NOT NULL,
`galleryCreatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
`galleryUpdatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`galleryIdentify` VARCHAR(50)  NOT NULL,
FOREIGN KEY (`eventId`) REFERENCES `events`(`eventId`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;