CREATE TABLE `inquiries` (
`inquiryId` INT  PRIMARY KEY NOT NULL AUTO_INCREMENT,
`name` VARCHAR(100)  NOT NULL,
`email` VARCHAR(150)  NOT NULL,
`phone` VARCHAR(20)  NULL,
`eventType` VARCHAR(100)  NOT NULL,
`message` TEXT  NOT NULL,
`inquiryCreatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
`inquiryUpdatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`inquiryIdentify` VARCHAR(50)  NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;