CREATE TABLE `media` (
`mediaId` INT  PRIMARY KEY NOT NULL AUTO_INCREMENT,
`media` VARCHAR(255)  NULL,
`mediaType` ENUM('post', 'product')  NULL,
`mediumCreatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
`mediumUpdatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`mediumIdentify` VARCHAR(50)  NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;