CREATE TABLE `meta_seo` (
`id` INT  PRIMARY KEY NOT NULL AUTO_INCREMENT,
`pageSlug` VARCHAR(255)  NULL,
`metaTitle` VARCHAR(255)  NULL,
`metaDescription` VARCHAR(500)  NULL,
`metaKeywords` VARCHAR(500)  NULL,
`imageFeature` VARCHAR(255)  NULL,
`imageAlt` VARCHAR(255)  NULL,
`canonicalURL` VARCHAR(255)  NULL,
`metaAuthor` VARCHAR(255)  NULL,
`meta_seoCreatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
`meta_seoUpdatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`meta_seoIdentify` VARCHAR(50)  NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;