CREATE TABLE `portfolio` (
`portfolioId` INT  PRIMARY KEY NOT NULL AUTO_INCREMENT,
`eventId` INT  NOT NULL,
`galleryImage` VARCHAR(255)  NOT NULL,
`caption` VARCHAR(150)  NULL,
`portfolioCreatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
`portfolioUpdatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`portfolioIdentify` VARCHAR(50)  NOT NULL,
FOREIGN KEY (`eventId`) REFERENCES `events`(`eventId`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;