CREATE TABLE `post` (
`postId` INT  PRIMARY KEY NULL AUTO_INCREMENT,
`postTitle` VARCHAR(250)  NULL,
`postDesc` VARCHAR(250)  NULL,
`postImg` VARCHAR(250)  UNIQUE NULL,
`postType` ENUM('a', 'b', 'c')  NOT NULL,
`postboolean` VARCHAR(255)  NOT NULL,
`postFloat` VARCHAR(255)  NOT NULL,
`postCreatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
`postUpdatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`postIdentify` VARCHAR(50)  NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;