CREATE TABLE `settings` (
`settingId` INT  PRIMARY KEY NOT NULL AUTO_INCREMENT,
`settingKey` VARCHAR(250)  NULL,
`settingValue` VARCHAR(250)  NULL,
`settingCreatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
`settingUpdatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`settingIdentify` VARCHAR(50)  NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;