CREATE TABLE `teams` (
`teamId` INT  PRIMARY KEY NOT NULL AUTO_INCREMENT,
`memberName` VARCHAR(250)  NULL,
`designation` VARCHAR(250)  NULL,
`email` VARCHAR(250)  NULL,
`mobile` VARCHAR(250)  NULL,
`profileImage` VARCHAR(255)  NULL,
`bio` VARCHAR(500)  NULL,
`teamCreatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
`teamUpdatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`teamIdentify` VARCHAR(50)  NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;