CREATE TABLE `teamMembers` (
`memberId` INT  PRIMARY KEY NOT NULL AUTO_INCREMENT,
`name` VARCHAR(100)  NOT NULL,
`role` VARCHAR(100)  NOT NULL,
`photo` VARCHAR(255)  NULL,
`bio` TEXT  NULL,
`socialLinks` TEXT  NULL,
`teamMemberCreatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
`teamMemberUpdatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`teamMemberIdentify` VARCHAR(50)  NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;