CREATE TABLE `testimonials` (
`testimonialId` INT  PRIMARY KEY NOT NULL AUTO_INCREMENT,
`clientName` VARCHAR(250)  NULL,
`clientCompany` VARCHAR(250)  NULL,
`testimonialText` VARCHAR(1000)  NULL,
`clientImage` VARCHAR(255)  NULL,
`testimonialCreatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
`testimonialUpdatedAt` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`testimonialIdentify` VARCHAR(50)  NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;